import { Artwork } from '@/types';

export const artworks: Artwork[] = [
  {
    id: '1',
    title: 'Coucher de Soleil Abstrait',
    artist: 'Souad Aziz',
    price: 4750,
    image: '/images/artworks/IMG-20250825-WA0008.jpg',
    description: 'Une œuvre vibrante capturant l\'essence d\'un coucher de soleil à travers des formes abstraites et des couleurs chaudes.',
    category: 'Abstrait',
    dimensions: '60 x 80 cm',
    technique: 'Acrylique sur toile',
    available: true,
  },
  {
    id: '2',
    title: 'Paysage Montagneux',
    artist: 'Souad Aziz',
    price: 3360,
    image: '/images/artworks/IMG-20250825-WA0007.jpg',
    description: 'Un paysage serein des montagnes de l\'Atlas, peint avec une technique impressionniste moderne.',
    category: 'Paysage',
    dimensions: '50 x 70 cm',
    technique: 'Huile sur toile',
    available: true,
  },
  {
    id: '3',
    title: 'Fleurs du Désert',
    artist: 'Souad Aziz',
    price: 2940,
    image: '/images/artworks/IMG-20250825-WA0006.jpg',
    description: 'Une composition délicate de fleurs du désert marocain, aux couleurs vives et contrastées.',
    category: 'Nature',
    dimensions: '40 x 50 cm',
    technique: 'Aquarelle',
    available: true,
  },
  {
    id: '4',
    title: 'Médina Nocturne',
    artist: 'Souad Aziz',
    price: 6090,
    image: '/images/artworks/IMG-20250825-WA0005.jpg',
    description: 'Les ruelles illuminées de la médina de Marrakech, capturées dans une ambiance mystérieuse.',
    category: 'Urbain',
    dimensions: '70 x 100 cm',
    technique: 'Technique mixte',
    available: true,
  },
  {
    id: '5',
    title: 'Danse des Couleurs',
    artist: 'Souad Aziz',
    price: 4410,
    image: '/images/artworks/IMG-20250825-WA0004.jpg',
    description: 'Une explosion de couleurs vives qui évoque la joie et le mouvement de la danse traditionnelle.',
    category: 'Abstrait',
    dimensions: '80 x 80 cm',
    technique: 'Acrylique sur toile',
    available: true,
  },
  {
    id: '6',
    title: 'Portrait Berbère',
    artist: 'Souad Aziz',
    price: 3990,
    image: '/images/artworks/IMG-20250825-WA0003.jpg',
    description: 'Un portrait expressif célébrant la beauté et la dignité de la culture berbère.',
    category: 'Portrait',
    dimensions: '50 x 60 cm',
    technique: 'Huile sur toile',
    available: true,
  },
  {
    id: '7',
    title: 'Jardin Andalou',
    artist: 'Souad Aziz',
    price: 5460,
    image: '/images/artworks/IMG-20250825-WA0002.jpg', // Exemple avec image locale
    description: 'Un jardin luxuriant inspiré des patios andalous, avec ses fontaines et sa végétation exotique.',
    category: 'Nature',
    dimensions: '65 x 85 cm',
    technique: 'Acrylique sur toile',
    available: false,
  },
];

export const categories = [
  'Tous',
  'Abstrait',
  'Paysage',
  'Nature',
  'Urbain',
  'Portrait',
];

export const heroImages = [
  'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1920&h=1080&fit=crop',
  'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=1080&fit=crop',
  'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1920&h=1080&fit=crop',
];
