import { Artwork } from '@/types';

export const artworks: Artwork[] = [
  {
    id: '1',
    title:'Eau d\'Azur',
    artist:'Souad Aziz',
    price:3000,
    image: '/images/artworks/EaudAzur.jpg',
    images: [
      '/images/artworks/EaudAzur.jpg',
      '/images/artworks/EaudAzur-2.jpg',
      '/images/artworks/EaudAzur-3.jpg'
    ],
    description: 'Ce mélange de couleur douce et apaisante, inspire la méditation et la sérénité.',
    category: 'Abstrait',
    dimensions: '100 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '2',
    title: 'Secret Garden',
    artist: 'Souad Aziz',
    price: 3360,
    image: '/images/artworks/SecretGarden.jpg',
    images: [
      '/images/artworks/SecretGarden.jpg',
      '/images/artworks/SecretGarden-2.jpg',
      '/images/artworks/SecretGarden-3.jpg'
    ],
    description: 'Une explosion de couleurs harmonieuse inspirée de la beauté florale.',
    category: 'Abstrait',
    dimensions: '100 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '3',
    title: 'Senteurs de bois',
    artist: 'Souad Aziz',
    price: 4000,
    image: '/images/artworks/senteursdebois.jpg',
    images: [
      '/images/artworks/senteursdebois.jpg',
      '/images/artworks/senteursdebois-2.jpg',
      '/images/artworks/senteursdebois-3.jpg'
    ],
    description: 'Ce tableau est le troisième de la série « WOOD FRAGRANCE », le mélange de couleur et leur mouvement nous emmène dans un voyage boisé.',
    category: 'Abstrait',
    dimensions: '140 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '4',
    title: 'Fleur d\'orient',
    artist: 'Souad Aziz',
    price: 3000,
    image: '/images/artworks/Fleurdorient.jpg',
    images: [
      '/images/artworks/Fleurdorient.jpg',
      '/images/artworks/Fleurdorient-2.jpg',
      '/images/artworks/Fleurdorient-3.jpg'
    ],
    description: 'Ce beau mélange de couleurs apaisante est inspiré de la beauté des plantes aquatiques.',
    category: 'Abstrait',
    dimensions: '100 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '5',
    title: 'Summer Rain',
    artist: 'Souad Aziz',
    price: 4400,
    image: '/images/artworks/SummerRain.jpg',
    images: [
      '/images/artworks/SummerRain.jpg',
      '/images/artworks/SummerRain-2.jpg',
      '/images/artworks/SummerRain-3.jpg'
    ],
    description: 'inspiré du Ciel d\'été.',
    category: 'Abstrait',
    dimensions: '140 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '6',
    title: 'Sandalwood',
    artist: 'Souad Aziz',
    price: 3500,
    image: '/images/artworks/sandalwood.jpg',
    images: [
      '/images/artworks/sandalwood.jpg',
      '/images/artworks/sandalwood-2.jpg'
    ],
    description: 'Ce tableau est le premier de la série « WOOD FRAGRANCE », le mélange de couleur et leur mouvement nous emmène dans un voyage boisé.',
    category: 'Abstrait',
    dimensions: '120 x 80 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2022,
  },
  {
    id: '7',
    title: 'Oud',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/oud.jpg',
    images: [
      '/images/artworks/oud.jpg',
      '/images/artworks/oud-2.jpg'
    ],
    description: 'Ce tableau est le deuxième de la série « WOOD FRAGRANCE », le mélange de couleur et leur mouvement nous emmène dans un voyage boisé.',
    category: 'Abstrait',
    dimensions: '70 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2022,
  },
  {
    id: '8',
    title: 'Serenity',
    artist: 'Souad Aziz',
    price: 4000,
    image: '/images/artworks/serenity.jpg',
    images: [
      '/images/artworks/serenity.jpg',
      '/images/artworks/serenity-2.jpg',
      '/images/artworks/serenity-3.jpg'

    ],
    description: 'excellent mélange de couleur douce et apaisante, inspire la méditation et la sérénité.',
    category: 'Abstrait',
    dimensions: '150 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '9',
    title: 'Vague de douceur',
    artist: 'Souad Aziz',
    price: 3500,
    image: '/images/artworks/vaguededouceur.jpg',
    images: [
      '/images/artworks/vaguededouceur.jpg',
      '/images/artworks/vaguededouceur-2.jpg',
      '/images/artworks/vaguededouceur-3.jpg' 
    ],
    description: 'excellent mélange de couleur douce et apaisante, inspire la méditation et la sérénité.',
    category: 'Abstrait',
    dimensions: 'Triptyque 80 x 55 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2023,
  },
  {
    id: '10',
    title: 'Explosion',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/explosion.jpg',
    images: [
      '/images/artworks/explosion.jpg'
    ],
    description: 'Explosion de couleurs entre le blanc et le noir.',
    category: 'Abstrait',
    dimensions: 'Triptyque 60 x 40 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2022,
  },
  {
    id: '11',
    title: 'Black\'n more',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/Blacknmore.jpg',
    images: [
      '/images/artworks/Blacknmore.jpg'
    ],
    description: 'Explosion de couleurs brisant le noir, ce qui reflète la vie en toutes ses composantes.',
    category: 'Abstrait',
    dimensions: '70 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2021,
  },
  {
    id: '12',
    title: 'Vortex',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/vortex.jpg',
    images: [
      '/images/artworks/vortex.jpg'
    ],
    description: 'Mélange et mouvement de couleurs, inspirés de l\'ambiance floral.',
    category: 'Abstrait',
    dimensions: 'Diptyque 60 x 40 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '13',
    title: 'Wisteria',
    artist: 'Souad Aziz',
    price: 2200,
    image: '/images/artworks/wisteria.jpg',
    images: [
      '/images/artworks/wisteria.jpg',
      '/images/artworks/wisteria-2.jpg',
      '/images/artworks/wisteria-3.jpg'
    ],
    description: 'Inspirée de la Wistéria,  ce mariage de couleurs reflète l\'harmonie et l\'élégance.',
    category: 'Abstrait',
    dimensions: ' 90 x 90 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2023,
  },
  {
    id: '14',
    title: 'Joy',
    artist: 'Souad Aziz',
    price: 4000,
    image: '/images/artworks/joy.jpg',
    images: [
      '/images/artworks/joy.jpg',
      '/images/artworks/joy-2.jpg',
      '/images/artworks/joy-3.jpg'
    ],
    description: 'Beau mélange de couleurs vivantes dans des mouvements harmonieux, inspire la joie de vivre.',
    category: 'Abstrait',
    dimensions: ' Triptyque 70 x 100 - 130 x 100 - 70 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '15',
    title: 'La lagune',
    artist: 'Souad Aziz',
    price: 3500,
    image: '/images/artworks/lagune.jpg',
    images: [
      '/images/artworks/lagune.jpg',
      '/images/artworks/lagune-2.jpg',
      '/images/artworks/lagune-3.jpg'
    ],
    description: 'une harmonie de couleurs douces, inspiration de l\'harmonie entre le ciel et l\'eau.',
    category: 'Abstrait',
    dimensions: ' 140 x 90 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '16',
    title: 'Lotus valley',
    artist: 'Souad Aziz',
    price: 3500,
    image: '/images/artworks/lotusvalley.jpg',
    images: [
      '/images/artworks/lotusvalley.jpg',
      '/images/artworks/lotusvalley-2.jpg',
      '/images/artworks/lotusvalley-3.jpg'
    ],
    description: 'Une harmonie de couleurs douces, inspiration de la fleur de lotus.',
    category: 'Abstrait',
    dimensions: ' 140 x 90 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '17',
    title: 'Thalassa',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/thalassa.jpg',
    images: [
      '/images/artworks/thalassa.jpg',
      '/images/artworks/thalassa-2.jpg'
      
    ],
    description: 'Une très joli mélange de couleur qui inspiré de la beauté des profondeurs marines.',
    category: 'Abstrait',
    dimensions: ' 140 x 90 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '18',
    title: 'Elia',
    artist: 'Souad Aziz',
    price: 2000,
    image: '/images/artworks/Elia.jpg',
    images: [
      '/images/artworks/Elia.jpg',
      '/images/artworks/Elia-2.jpg',
      '/images/artworks/Elia-3.jpg'
    ],
    description: 'inspiration du thème floral.',
    category: 'Abstrait',
    dimensions: ' Triptyque circulaire 60 - 50 - 40 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '19',
    title: 'Le regard',
    artist: 'Souad Aziz',
    price: 1500,
    image: '/images/artworks/LeRegard.jpg',
    images: [
      '/images/artworks/LeRegard.jpg'
    ],
    description: 'ENCOURS.',
    category: 'Abstrait',
    dimensions: ' 60 x 40 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2025,
  },
  {
    id: '20',
    title: 'L\'envolée blanche',
    artist: 'Souad Aziz',
    price: 1500,
    image: '/images/artworks/envoléeBlanche.jpg',
    images: [
      '/images/artworks/envoléeBlanche.jpg'
    ],
    description: 'la danseuse amazigh du moyen atlas modernisée, un mixte de tradition dans l\'identité et le classicisme de la dance, ce tableau est une capture de mouvement en suspension, une dance d\'esprit.',
    category: 'Abstrait',
    dimensions: ' 100 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2025,
  },
  {
    id: '21',
    title: 'Miroir des Eaux',
    artist: 'Souad Aziz',
    price: 1500,
    image: '/images/artworks/IMG-20250825-WA0002.jpg',
    images: [
      '/images/artworks/IMG-20250825-WA0002.jpg'
    ],
    description: 'excellent mélange de couleur mouvementé, en le méditant, on voyage dans nos profondeurs.',
    category: 'Abstrait',
    dimensions: ' Cerculaire 60 cm',
    technique: 'Technique mixte sur toile',
    available: true,
    year: 2025,
  },
  {
    id: '22',
    title: 'Tierra-Mar',
    artist: 'Souad Aziz',
    price: 3000,
    image: '/images/artworks/tierra-mar.jpg',
    images: [
      '/images/artworks/tierra-mar.jpg',
      '/images/artworks/tierra-mar-2.jpg',
      '/images/artworks/tierra-mar-3.jpg'
    ],
    description: 'Une explosion de couleurs vives représentant la complémentarité entre vie terrestre et marine, évoquant le mouvement de l\'existence.',
    category: 'Abstrait',
    dimensions: ' 100 x 70 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '23',
    title: 'Fall',
    artist: 'Souad Aziz',
    price: 3000,
    image: '/images/artworks/fall.jpg',
    images: [
      '/images/artworks/fall.jpg',
      '/images/artworks/fall-2.jpg'
      
    ],
    description: 'Un paysage travaillé avec un mariage de couleurs douce parfait pour les amoureux de l\'ambiance  automnale.',
    category: 'Abstrait',
    dimensions: ' 100 x 100 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
  {
    id: '24',
    title: 'Reflexion',
    artist: 'Souad Aziz',
    price: 1500,
    image: '/images/artworks/reflexion.jpg',
    images: [
      '/images/artworks/reflexion.jpg',
      '/images/artworks/reflexion-2.jpg'
    ],
    description: 'Excellent mélange de couleur douce et apaisante, inspire la méditation et la sérénité.',
    category: 'Abstrait',
    dimensions: ' Cerculaire 60 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2024,
  },
  {
    id: '25',
    title: 'les chemins du pardon',
    artist: 'Souad Aziz',
    price: 4500,
    image: '/images/artworks/lescheminsdupardon.jpg',
    images: [
      '/images/artworks/lescheminsdupardon.jpg',
      '/images/artworks/lescheminsdupardon-2.jpg',
      '/images/artworks/lescheminsdupardon-3.jpg'
    ],
    description: 'Ce tableau se distingue par sa composition de couleurs douce et harmonieuse mais mouvementée, et qui apporte un message spirituel profond.',
    category: 'Abstrait',
    dimensions: ' 140 x 80 cm',
    technique: 'Technique mixte sur toile',
    available: false,
    year: 2022,
  },
];

export const categories = [
  'Tous',
  'Abstrait',
  'Paysage',
  'Nature',
  'Urbain',
  'Portrait',
];

export const heroImages = [
  '/images/hero.jpg',
  '/images/hero-2.jpg',
  '/images/hero-3.jpg',
];
